# Generated by Django 5.1.2 on 2024-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
