# Generated by Django 5.1.2 on 2024-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('about_us', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('cookies_policy', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
