# Generated by Django 5.1.2 on 2024-10-28 23:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_facebook_sitesettings_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cookies_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='disclaimer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy_policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms_and_conditions',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
